require:
  - rubocop-inhouse

inherit_gem:
  rubocop-inhouse:
    - config/default.yml

Metrics/BlockLength:
  Exclude:
    - app/layouts/*.rb
    - app/pages/*.rb

Metrics/MethodLength:
  Exclude:
    - app/layouts/*.rb
    - app/pages/*.rb

Metrics/AbcSize:
  Exclude:
    - app/layouts/*.rb
    - app/pages/*.rb
