# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in staticky.gemspec
gemspec

gem "capybara"
gem "dry-files", github: "nolantait/dry-files", branch: "entries-nt"
gem "debug"
gem "rake"
gem "rspec"
gem "rubocop-inhouse", require: false

